[project]
name = "arcade-coding-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.6",
    "djangorestframework>=3.15.2",
    "pytest>=8.3.5",
    "pytest-django>=4.10.0",
]
